require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.theme")

require("user.plugins.impatient")

require("user.plugins.alpha")
-- require("user.plugins.autopairs")
-- require("user.plugins.bufferline")
require("user.plugins.cmp")
require("user.plugins.comment")
require("user.plugins.gitsigns")
require("user.plugins.indentline")
require("user.plugins.lsp")
require("user.plugins.lualine")
require("user.plugins.nvim-tree")
require("user.plugins.telescope")
require("user.plugins.treesitter")

